<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.36"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.36" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared\MyPortfolio.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\images\projects\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="wwwroot\images\projects\agam\.DS_Store" />
    </ItemGroup>

</Project>
